--CATEGORIAS
INSERT INTO category (name, description, image) VALUES ('Acción', 'Videojuegos centrados en el combate, los reflejos y el dinamismo.', '/images/categoriaAccion.png');
INSERT INTO category (name, description, image) VALUES ('Aventura', 'Videojuegos centrados en la exploración, la historia y la resolución de puzzles, con mundos inmersivos y narrativas épicas.', '/images/categoriaAventura.png');
INSERT INTO category (name, description, image) VALUES ('Deportes', 'Juegos basados en disciplinas deportivas como fútbol, baloncesto, ...', '/images/categoriaDeportes.png');
INSERT INTO category (name, description, image) VALUES ('Estrategia', 'Títulos que requieren planificación táctica y toma de decisiones.', '/images/categoriaEstrategia.png');
INSERT INTO category (name, description, image) VALUES ('RPG', 'Role Playing Games donde el jugador progresa y desarrolla habilidades.', '/images/categoriaRPG.png');
INSERT INTO category (name, description, image) VALUES ('Carreras', 'Videojuegos centrados en competencias de velocidad con vehículos.', '/images/categoriaCarreras.png');
INSERT INTO category (name, description, image) VALUES ('Simulación', 'Juegos que recrean experiencias de la vida real o actividades especializadas.', '/images/categoriaSimulacion.png');
INSERT INTO category (name, description, image) VALUES ('Battle Royale', 'Multijugador de supervivencia donde muchos jugadores compiten hasta quedar uno.', '/images/categoriaBattleRoyale.png');
INSERT INTO category (name, description, image) VALUES ('Lucha', 'Ofrecen combates intensos entre personajes con habilidades únicas, ideal para quienes disfrutan de la acción rápida y estratégica.', NULL);

--PRODUCTOS
INSERT INTO product (name, description, category, brand, image, ean) VALUES
                    ('Shadow Strike', 'Shadow Strike es un juego de acción trepidante donde cada decisión puede cambiar el destino del mundo. Con niveles complejos y enemigos desafiantes, requiere habilidad y estrategia.', 'Accion', 'DarkGames', '/images/products/shadowStrike.png', '4006381333931'),
                    ('Adventure Quest', 'Embárcate en una aventura épica llena de misterios y acertijos que pondrán a prueba tu ingenio en cada paso.', 'Aventura', 'EpicStudios', NULL, '4006381333948'),
                    ('Ultimate Soccer 2026', 'Disfruta del fútbol más realista jamás creado, con estadísticas de jugadores actualizadas, modos multijugador online y simulación avanzada de partidos.', 'Deporte', NULL, '/images/products/ultimateSoccer2026.png', '4006381333955'),
                    ('Castle Strategist', 'Conviértete en el maestro de la estrategia medieval. Planea ataques, gestiona recursos y domina los castillos enemigos con tus tácticas.', 'Estrategia', 'MedievalGames', '/images/products/castleStrategist.png', '4006381333962'),
                    ('Fantasy RPG Legends', 'Sumérgete en un mundo de fantasía donde la magia y la aventura se entrelazan en una historia profunda y emocionante que abarca cientos de horas de juego.', 'RPG', 'FantasyWorks', NULL, '4006381333979'),
                    ('Speed Racers', 'Compite a toda velocidad en circuitos urbanos y rurales, personaliza tus coches y domina los modos de carrera más desafiantes.', 'Carreras', NULL, '/images/products/speedRacers.png', '4006381333986'),
                    ('SimLife Tycoon', 'Gestiona tu propia ciudad virtual, controla la economía, servicios y la felicidad de los ciudadanos en un simulador que desafía tu creatividad.', 'Simulacion', 'SimSoft', NULL, '4006381333993'),
                    ('Battle Royale Extreme', 'Entra en la arena definitiva donde solo puede quedar uno. Recoge armas, estrategia y supervivencia se combinan para la experiencia más intensa.', 'Battle Royale', NULL, '/images/products/battleRoyaleExtreme.png', '4006381334006'),
                    ('Ultimate Fighters', 'Domina combates épicos en arenas de lucha, cada personaje con habilidades únicas y combos devastadores que solo los mejores podrán ejecutar.', 'Lucha', 'FightClub', '/images/products/ultimateFighters.png', '4006381334013'),
                    ('Action Hero 2', 'La secuela más esperada trae explosiones, persecuciones y misiones de alto riesgo en un mundo abierto lleno de desafíos y secretos por descubrir.', 'Accion', NULL, NULL, '4006381334020'),
                    ('Mystery Island', 'Explora una isla remota llena de misterios, enemigos y puzzles que pondrán a prueba tu ingenio mientras descubres la historia oculta de sus habitantes.', 'Aventura', 'IslandGames', '/images/products/mysteryIsland.png', '4006381334037'),
                    ('Pro Basketball 2026', 'Lleva tu equipo a la gloria en competiciones profesionales con inteligencia artificial avanzada y modos multijugador online para desafiar a tus amigos.', 'Deporte', 'SportsWorld', NULL, '4006381334044'),
                    ('War Tactics', 'Planea guerras épicas en mapas estratégicos detallados, gestionando tropas, recursos y alianzas en tiempo real para dominar a tus oponentes.', 'Estrategia', NULL, '/images/products/warTactics.png', '4006381334051'),
                    ('Dragon Realms', 'Una aventura RPG de fantasía profunda con dragones, hechicería y mundos extensos que garantizan cientos de horas de exploración y combate.', 'RPG', 'DragonStudios', '/images/products/dragonRealms.png', '4006381334068'),
                    ('Formula Extreme', 'Siente la adrenalina de las carreras de fórmula en circuitos internacionales con físicas realistas y opciones de personalización únicas.', 'Carreras', 'FastGames', NULL, '4006381334075'),
                    ('City Builder Deluxe', 'Diseña y administra tu propia metrópoli con gran detalle, equilibrando economía, infraestructura y servicios para mantener a tus ciudadanos felices.', 'Simulacion', NULL, '/images/products/cityBuilderDeluxe.png', '4006381334082'),
                    ('Survival Arena', 'Prepárate para sobrevivir en la arena de batalla más implacable, donde cada decisión estratégica puede significar la diferencia entre la vida y la muerte.', 'Battle Royale', 'SurvivorGames', NULL, '4006381334099'),
                    ('Fight Masters', 'Conviértete en el mejor luchador del mundo enfrentándote a rivales con estilos únicos y combos espectaculares que solo los expertos dominarán.', 'Lucha', NULL, '/images/products/fightMasters.png', '4006381334105'),
                    ('Action Legends', 'Una colección de misiones de acción épicas donde el jugador experimenta diferentes estilos de combate, explosiones y persecuciones sin fin.', 'Accion', 'LegendaryGames', '/images/products/actionLegends.png', '4006381334112'),
                    ('Adventure World', 'Explora mundos vibrantes y llenos de secretos, interactuando con personajes únicos y completando misiones que desafían tu ingenio y habilidades.', 'Aventura', NULL, NULL, '4006381334129');
