spring.application.name=shop-eah-jdr-api
spring.datasource.url=jdbc:h2:mem:shop;DATABASE_TO_LOWER=TRUE
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.defer-datasource-initialization=true
#server.servlet.context-path=/path/simulado/para-pruebas

jwt.secret=Hola_esto_tiene_que_tener_al_menos_32_carcteres_para_que_funcione.
jwt.access-token.expiration=30000000
jwt.refresh-token.expiration=30000000
server.port=8000
